# Change these first
owner: deutsch-thomas # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository 

sites:
  - name: Grafana
    url: https://monitor.bluectrl.app/
  - name: InfluxDB
    url: https://monitor.bluectrl.app:8443/
  - name: RabbitMQ
    url: https://monitor.bluectrl.app:15672/
  - name: Loki
    url: https://monitor.bluectrl.app:3100/
    expectedStatusCodes:
      - 401
  - name: Live-BlueCtrl
    url: https://bluectrl.app
  - name: BlueCtrl-CFE
    url: https://bluectrl.cfe-computing.com
    maxResponseTime: 5000
  - name: Stage-BlueCtrl-CFE
    url: https://stage.bluectrl.cfe-computing.com
  - name: Dev-BlueCtrl-CFE
    url: https://dev.bluectrl.cfe-computing.com
  - name: Demo-BlueCtrl-CFE
    url: https://demo.bluectrl.cfe-computing.com
  - name: Live-API-BlueCtrl
    url: https://api.bluectrl.app/docs#/
  - name: API-BlueCtrl-CFE
    url: https://api.cfe-computing.com/docs
  - name: Stage-API-BlueCtrl-CFE
    url: https://dev.api.cfe-computing.com/docs
  - name: Dev-API-BlueCtrl-CFE
    url: https://stage.api.cfe-computing.com/docs
  - name: DemoAPI-BlueCtrl-CFE
    url: https://demo.api.cfe-computing.com/docs
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.cfe-computing.com
  # baseUrl: /upptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime** Service."
  introMessage: Hier siehst du den Status aller überwachten Services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration 
